### PR TITLE
Feature: add statemachine for dledger

### PR DESCRIPTION
**Pull request by hzh0425**
# What is the purpose of the change
Add a state machine for dledger, support apply, snapshotSave, snapshotLoad.

### CODE REVIEW

**Comment by vongosling** [comment]
@hzh0425 Do you prepare for our 2022 summer program which is hosted by the Chinese Academy of Sciences? If not, I recommend you sign up. This is one of our topic this year.

**Comment by hzh0425** [comment]
> 

Yes, I participated, I know there is another snapshot topic, but I will add the state machine first, so that another contributor can do this topic later. Maybe @RongtongJin can take a look.

**Comment by hzh0425** [comment]
@Yes, I participated, I know there is another snapshot topic, but I will add the state machine first, so that another contributor can do this topic later. Maybe @RongtongJin can take a look.

**Comment by hzh0425** [comment]
@vongosling I participated, I know there is another snapshot topic, but I will add the state machine first, so that another contributor can do this topic later. Maybe @RongtongJin can take a look.

**Comment by vongosling** [comment]
Nice, Jin is one of our mentors.

**Comment by hzh0425** [comment]
@vongosling yep, Actually, I'm on another topic, the mentor is Jin, but the topic need to add a state machine to the dledger first.

**Review by RongtongJin — APPROVED** [review]

**Pull request merged**
