### PR TITLE
Add Statemachine feature for DLedger

### PR DESCRIPTION
**Pull request by RongtongJin**
Add Statemachine feature for DLedger

### CODE REVIEW

**Comment by RongtongJin** [comment]
@yuz10 Could you help review this PR? Statemachine feature will not affect normal processes if not use.

**Comment by RongtongJin** [comment]
> while (iter.hasNext()) is also called in statemachine.onApply, and why do we complete client response in iter.hasNext(), before the statemachine is really applied



> while (iter.hasNext()) is also called in statemachine.onApply, and why do we complete client response in iter.hasNext(), before the statemachine is really applied

其实这里是complete上一个的，就是已经被apply的

**Comment by hzh0425** [comment]
> while (iter.hasNext()) is also called in statemachine.onApply, and why do we complete c

yep, complete the pre entryResponseFuture

**Review by ShannonDing — APPROVED** [review]
LGTM

**Review by yuz10 — APPROVED** [review]

**Review by cserwen — APPROVED** [review]

**Review by odbozhou — APPROVED** [review]

**Comment by cserwen** [comment]
@hzh0425  There are some errors in the unit test.

**Comment by hzh0425** [comment]
@cserwen hi, i have fixed the bug in https://github.com/openmessaging/dledger/pull/139, 
except (DLedgerMappedFileStoreTest # testAbnormalRecovery ), it can't even run successfully in the old version

**Comment by cserwen** [comment]
> except

I can successfully execute the test in the latest version.  Maybe it's failed because of other reasons, not a bug.:-D

**Pull request merged**
